### ISSUE TITLE
Launch on Mac OS fails

### ISSUE THREAD

**Issue by y28xml** [DougReynolds/AF_Diffraction_Spikes#2]
**Describe the bug**
When following the instructions to install python with brew and all dependencies, an error occurs when trying to start the tool.
Error message:
python3 AF_diffraction_spikes_gui.py
Traceback (most recent call last):
  File "../AF_Diffraction_Spikes-main/AF_diffraction_spikes_gui.py", line 1, in <module>
    from ImageProcessor import ImageProcessor
  File "../AF_Diffraction_Spikes-main/ImageProcessor.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Desktop (please complete the following information):**
 - Mac Studio
 - OS: MacOS 15.2 Sequoia 
 - CPU: M1 Max

**Comment by DougReynolds** [comment]
@y28xml Please see the latest release, information in the readme.  Additionally, I have created a Mac installer found in the V2 release.
Cheers!
Doug
